version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweqwe33
      POSTGRES_DB: file_uploader
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d file_uploader"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://postgres:qweqwe33@db:5432/file_uploader?sslmode=disable",
      "up"
    ]
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
